import Footer from '@/components/Shard/Footer/Footer';
import NavBar from '@/components/Shard/NavBar/NavBar';
import TopHeader from '@/components/Ui/TopHead/TopHeader';

export const metadata = {
  title: 'TheTastEat- Contact page',
  description: 'Generated by TheTastEat',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopHeader />
        {/* <Nav /> */}
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
